"""Initial migration

Revision ID: 088dc53612e1
Revises: 
Create Date: 2024-12-08 23:01:41.721200

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '088dc53612e1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_example_model_name', table_name='example_model')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_example_model_name', 'example_model', ['name'], unique=False)
    # ### end Alembic commands ###
