"""added the requested important features

Revision ID: 0a8f81d96ca4
Revises: 088dc53612e1
Create Date: 2024-12-09 12:17:39.306388

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a8f81d96ca4'
down_revision: Union[str, None] = '088dc53612e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_bot_settings_id'), 'bot_settings', ['id'], unique=False)
    op.add_column('managed_servers', sa.Column('notification_channel_id', sa.String(), nullable=True))
    op.add_column('managed_servers', sa.Column('initial_vote_tag_id', sa.String(), nullable=True))
    op.add_column('managed_servers', sa.Column('added_to_list_tag_id', sa.String(), nullable=True))
    op.add_column('managed_servers', sa.Column('not_in_list_tag_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_managed_servers_id'), 'managed_servers', ['id'], unique=False)
    op.create_index(op.f('ix_valid_tags_id'), 'valid_tags', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_valid_tags_id'), table_name='valid_tags')
    op.drop_index(op.f('ix_managed_servers_id'), table_name='managed_servers')
    op.drop_column('managed_servers', 'not_in_list_tag_id')
    op.drop_column('managed_servers', 'added_to_list_tag_id')
    op.drop_column('managed_servers', 'initial_vote_tag_id')
    op.drop_column('managed_servers', 'notification_channel_id')
    op.drop_index(op.f('ix_bot_settings_id'), table_name='bot_settings')
    # ### end Alembic commands ###
