"""new spreadsheet feature check

Revision ID: a231535cb121
Revises: 088dc53612e1
Create Date: 2024-12-09 05:50:40.669624

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a231535cb121'
down_revision: Union[str, None] = '088dc53612e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bot_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_index(op.f('ix_bot_settings_id'), 'bot_settings', ['id'], unique=False)
    op.create_table('managed_servers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('server_id', sa.String(), nullable=False),
    sa.Column('forum_channel_id', sa.String(), nullable=False),
    sa.Column('spreadsheet_id', sa.String(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('server_id')
    )
    op.create_index(op.f('ix_managed_servers_id'), 'managed_servers', ['id'], unique=False)
    op.create_table('valid_tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('server_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('tag_type', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('server_id', 'name', name='unique_tag_per_server')
    )
    op.create_index(op.f('ix_valid_tags_id'), 'valid_tags', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_valid_tags_id'), table_name='valid_tags')
    op.drop_table('valid_tags')
    op.drop_index(op.f('ix_managed_servers_id'), table_name='managed_servers')
    op.drop_table('managed_servers')
    op.drop_index(op.f('ix_bot_settings_id'), table_name='bot_settings')
    op.drop_table('bot_settings')
    # ### end Alembic commands ###
